name = "Text-Conceal"
badges = [ 'github-actions/test', 'metacpan' ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "master"
do_not_upload_to_cpan = 0

